locations = [
    "Tokyo, Japan",
    "Cape Town, South Africa",
    "Banff National Park, Canada",
    "Reykjavik, Iceland",
    "Timbuktu, Mali",
    "Ushuaia, Argentina",
    "Petra, Jordan",
    "Dubrovnik, Croatia",
    "Mount Kilimanjaro, Tanzania",
    "Tallinn, Estonia",
    "Bora Bora, French Polynesia",
    "Svalbard, Norway",
    "Machu Picchu, Peru",
    "Alice Springs, Australia",
    "Valparaíso, Chile",
    "Nuuk, Greenland",
    "Hallstatt, Austria",
    "Socotra Island, Yemen",
    "Rapa Nui (Easter Island), Chile",
    "Ljubljana, Slovenia",
    "Bagan, Myanmar",
    "Yakutsk, Russia",
    "Lake Baikal, Russia",
    "Antelope Canyon, USA",
    "Salar de Uyuni, Bolivia",
    "Luang Prabang, Laos",
    "Tórshavn, Faroe Islands",
    "Gobi Desert, Mongolia",
    "Matera, Italy",
    "Chichén Itzá, Mexico",
    "Lofoten Islands, Norway",
    "Tulum, Mexico",
    "Palawan, Philippines",
    "Meteora, Greece",
    "Queenstown, New Zealand",
    "Kotor, Montenegro",
    "Siwa Oasis, Egypt",
    "Hạ Long Bay, Vietnam",
    "Pripyat, Ukraine",
    "Carcassonne, France",
    "Dead Sea, Jordan/Israel",
    "Moab, Utah, USA",
    "Coober Pedy, Australia",
    "Isle of Skye, Scotland",
    "Jeju Island, South Korea",
    "Bhutan",
    "Medellín, Colombia",
    "Rotorua, New Zealand",
    "Wulingyuan, China",
    "Lake Titicaca, Peru/Bolivia",
    "Samarkand, Uzbekistan",
    "Lalibela, Ethiopia",
    "Big Sur, California, USA",
    "Angel Falls, Venezuela",
    "The Azores, Portugal",
    "Victoria Falls, Zambia/Zimbabwe",
    "Galápagos Islands, Ecuador",
    "Pamukkale, Turkey",
    "Bled, Slovenia",
    "San Pedro de Atacama, Chile",
    "Lake Tekapo, New Zealand",
    "Kakslauttanen, Finland",
    "Phong Nha-Kẻ Bàng, Vietnam",
    "Hoi An, Vietnam",
    "Torres del Paine, Chile",
    "Isfahan, Iran",
    "Vang Vieng, Laos",
    "The Alhambra, Spain",
    "Nara, Japan",
    "Jaisalmer, India",
    "White Desert, Egypt",
    "Zakopane, Poland",
    "Rovaniemi, Finland",
    "Aït Benhaddou, Morocco",
    "Masada, Israel",
    "Lake Louise, Canada",
    "Kakadu National Park, Australia",
    "Tashkent, Uzbekistan",
    "Inverness, Scotland",
    "Mont-Saint-Michel, France",
    "Dingle Peninsula, Ireland",
    "Gimmelwald, Switzerland",
    "Jiuzhaigou Valley, China",
    "Bariloche, Argentina",
    "Windhoek, Namibia",
    "Malé, Maldives",
    "Isle of Man, UK",
    "Sossusvlei, Namibia",
    "Agra, India",
    "Essaouira, Morocco",
    "Hvar, Croatia",
    "Charyn Canyon, Kazakhstan",
    "Lhasa, Tibet",
    "Sa Pa, Vietnam",
    "Gjirokastër, Albania",
    "Lake Toba, Indonesia",
    "Lesotho",
    "King’s Canyon, Australia",
    "Zanzibar, Tanzania",
    "Ericeira, Portugal"
]

company_names = [
    "Apex Dynamics",
    "Nimbus Innovations",
    "Bluewave Technologies",
    "Evergreen Solutions",
    "Quantum Logistics",
    "Pinnacle BioLabs",
    "Northbridge Ventures",
    "Silverline Consulting",
    "Vertex Health",
    "Lumina Energy",
    "NextGen Robotics",
    "Redwood Systems",
    "Arcturus Aerospace",
    "BrightPath Learning",
    "Crimson Creek Foods",
    "Summit Financial Group",
    "EchoLink Media",
    "Ironclad Security",
    "Cascade Apparel",
    "FusionCore Industries",
    "GreenHarvest Organics",
    "UrbanNest Realty",
    "Helix Pharmaceuticals",
    "Atlas Maritime",
    "CrystalBay Resorts",
    "Falcon Ridge Motors",
    "NovaGrid Electric",
    "PureWell Cosmetics",
    "Zenith Software Labs",
    "Vanguard Metals",
    "Sapphire Insights",
    "Trekora Outdoor Gear",
    "Starlight Studios",
    "Modular Works",
    "PolarPeak Outfitters",
    "Orbital Synergy",
    "Brightforge Engineering",
    "Cloudberry Analytics",
    "Stonegate Construction",
    "Solstice Wearables",
    "Neptune Shipping Co.",
    "Lighthouse Robotics",
    "Amberfield Ventures",
    "Velvet Fox Marketing",
    "Tundra Foods Inc.",
    "Oak & Iron Furniture",
    "Monarch Biotech",
    "Blue Harbor Networks",
    "Solartrail Renewables",
    "Nimble Panda Games",
    "Aspire Dynamics",
    "Zenpath Therapeutics",
    "Skyward Drones",
    "Ironroot Fabrication",
    "Kinetiq Digital",
    "Evercore Legal",
    "Mariner AI",
    "Brasswood Publishing",
    "Crescent Moon Bakery",
    "NovaLoom Textiles",
    "Stratus Insurance",
    "Firefly Mobility",
    "Cobalt Research Group",
    "DeepWave Data",
    "Halcyon Architecture",
    "Rainforest Imports",
    "Peregrine Aviation",
    "Lumenia Lighting",
    "EchoStone Media",
    "Vireo Health Systems",
    "Sunspire Agritech",
    "Atlas Forge Manufacturing",
    "Riverview Analytics",
    "Trellis Innovations",
    "Copper Canyon Brewing",
    "ForgeTech Labs",
    "Nimbus Electric Vehicles",
    "BrightBridge Capital",
    "Northern Echo AI",
    "Zephyr Security Systems",
    "Oceanleaf Travel",
    "Magnetar Ventures",
    "Sundial Ceramics",
    "Jetstream Solutions",
    "Verdant Earth Products",
    "Bayshore Financial",
    "Kairo Robotics",
    "Cloudwell Hosting",
    "Obsidian Automation",
    "Neon Arc Studios",
    "Marble & Mint Design Co.",
    "TerraNova Geotech",
    "CrystalForge Optics",
    "Twilight Digital",
    "Everreach Telecom",
    "Verdigris Labs",
    "Whitecap Holdings",
    "Driftwood Ventures",
    "Cascade Bioworks",
    "Solaris Biomechanics",
    "Alpenglow Strategy Group"
]

industries = [
    "Aerospace",
    "Agriculture",
    "Airlines",
    "Apparel & Fashion",
    "Architecture",
    "Automotive",
    "Aviation",
    "Banking",
    "Biotechnology",
    "Broadcast Media",
    "Building Materials",
    "Business Supplies & Equipment",
    "Capital Markets",
    "Chemicals",
    "Civic & Social Organization",
    "Civil Engineering",
    "Commercial Real Estate",
    "Computer & Network Security",
    "Computer Games",
    "Computer Hardware",
    "Computer Networking",
    "Computer Software",
    "Construction",
    "Consumer Electronics",
    "Consumer Goods",
    "Consumer Services",
    "Cosmetics",
    "Dairy",
    "Defense & Space",
    "Design",
    "E-Learning",
    "Education Management",
    "Electrical & Electronic Manufacturing",
    "Energy",
    "Engineering",
    "Entertainment",
    "Environmental Services",
    "Events Services",
    "Executive Office",
    "Facilities Services",
    "Farming",
    "Financial Services",
    "Fine Art",
    "Fishery",
    "Food & Beverages",
    "Food Production",
    "Fundraising",
    "Furniture",
    "Gambling & Casinos",
    "Glass, Ceramics & Concrete",
    "Government Administration",
    "Government Relations",
    "Graphic Design",
    "Health, Wellness & Fitness",
    "Higher Education",
    "Hospital & Health Care",
    "Hospitality",
    "Human Resources",
    "Import & Export",
    "Individual & Family Services",
    "Industrial Automation",
    "Information Services",
    "Information Technology & Services",
    "Insurance",
    "International Affairs",
    "International Trade & Development",
    "Internet",
    "Investment Banking",
    "Investment Management",
    "Judiciary",
    "Law Enforcement",
    "Law Practice",
    "Legal Services",
    "Legislative Office",
    "Leisure, Travel & Tourism",
    "Libraries",
    "Logistics & Supply Chain",
    "Luxury Goods & Jewelry",
    "Machinery",
    "Management Consulting",
    "Maritime",
    "Marketing & Advertising",
    "Market Research",
    "Mechanical or Industrial Engineering",
    "Media Production",
    "Medical Devices",
    "Medical Practice",
    "Mental Health Care",
    "Military",
    "Mining & Metals",
    "Mobile Games",
    "Motion Pictures & Film",
    "Museums & Institutions",
    "Music",
    "Nanotechnology",
    "Newspapers",
    "Nonprofit Organization Management",
    "Oil & Energy",
    "Online Media",
    "Outsourcing/Offshoring",
    "Package/Freight Delivery",
    "Packaging & Containers",
    "Paper & Forest Products",
    "Performing Arts",
    "Pharmaceuticals",
    "Philanthropy",
    "Photography",
    "Plastics",
    "Political Organization",
    "Primary/Secondary Education",
    "Printing",
    "Professional Training & Coaching",
    "Program Development",
    "Public Policy",
    "Public Relations & Communications",
    "Public Safety",
    "Publishing",
    "Railroad Manufacture",
    "Ranching",
    "Real Estate",
    "Recreational Facilities & Services",
    "Religious Institutions",
    "Renewables & Environment",
    "Research",
    "Restaurants",
    "Retail",
    "Security & Investigations",
    "Semiconductors",
    "Shipbuilding",
    "Sporting Goods",
    "Sports",
    "Staffing & Recruiting",
    "Supermarkets",
    "Telecommunications",
    "Textiles",
    "Think Tanks",
    "Tobacco",
    "Translation & Localization",
    "Transportation/Trucking/Railroad",
    "Utilities",
    "Venture Capital & Private Equity",
    "Veterinary",
    "Warehousing",
    "Wholesale",
    "Wine & Spirits",
    "Wireless",
    "Writing & Editing"
]

nationalities = [
    "Afghan",
    "Albanian",
    "Algerian",
    "American",
    "Andorran",
    "Angolan",
    "Argentine",
    "Armenian",
    "Australian",
    "Austrian",
    "Azerbaijani",
    "Bahamian",
    "Bahraini",
    "Bangladeshi",
    "Barbadian",
    "Belarusian",
    "Belgian",
    "Belizean",
    "Beninese",
    "Bhutanese",
    "Bolivian",
    "Bosnian",
    "Botswanan",
    "Brazilian",
    "British",
    "Bruneian",
    "Bulgarian",
    "Burkinabé",
    "Burmese",
    "Burundian",
    "Cambodian",
    "Cameroonian",
    "Canadian",
    "Cape Verdean",
    "Central African",
    "Chadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Comorian",
    "Congolese",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Cypriot",
    "Czech",
    "Danish",
    "Djiboutian",
    "Dominican",
    "Dutch",
    "East Timorese",
    "Ecuadorean",
    "Egyptian",
    "Emirati",
    "English",
    "Equatorial Guinean",
    "Eritrean",
    "Estonian",
    "Eswatini",
    "Ethiopian",
    "Fijian",
    "Finnish",
    "French",
    "Gabonese",
    "Gambian",
    "Georgian",
    "German",
    "Ghanaian",
    "Greek",
    "Grenadian",
    "Guatemalan",
    "Guinean",
    "Guyanese",
    "Haitian",
    "Honduran",
    "Hungarian",
    "Icelandic",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Ivorian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kazakhstani",
    "Kenyan",
    "Kiribati",
    "Korean",
    "Kosovar",
    "Kuwaiti",
    "Kyrgyzstani",
    "Lao",
    "Latvian",
    "Lebanese",
    "Liberian",
    "Libyan",
    "Liechtensteiner",
    "Lithuanian",
    "Luxembourgish",
    "Macedonian",
    "Malagasy",
    "Malawian",
    "Malaysian",
    "Maldivian",
    "Malian",
    "Maltese",
    "Marshallese",
    "Mauritanian",
    "Mauritian",
    "Mexican",
    "Micronesian",
    "Moldovan",
    "Monegasque",
    "Mongolian",
    "Montenegrin",
    "Moroccan",
    "Mozambican",
    "Namibian",
    "Nauruan",
    "Nepalese",
    "New Zealander",
    "Nicaraguan",
    "Nigerian",
    "Nigerien",
    "North Korean",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Palauan",
    "Palestinian",
    "Panamanian",
    "Papua New Guinean",
    "Paraguayan",
    "Peruvian",
    "Philippine",
    "Polish",
    "Portuguese",
    "Qatari",
    "Romanian",
    "Russian",
    "Rwandan",
    "Saint Lucian",
    "Salvadoran",
    "Samoan",
    "San Marinese",
    "Saudi",
    "Scottish",
    "Senegalese",
    "Serbian",
    "Seychellois",
    "Sierra Leonean",
    "Singaporean",
    "Slovak",
    "Slovenian",
    "Solomon Islander",
    "Somali",
    "South African",
    "South Korean",
    "Spanish",
    "Sri Lankan",
    "Sudanese",
    "Surinamese",
    "Swazi",
    "Swedish",
    "Swiss",
    "Syrian",
    "Taiwanese",
    "Tajikistani",
    "Tanzanian",
    "Thai",
    "Togolese",
    "Tongan",
    "Trinidadian",
    "Tunisian",
    "Turkish",
    "Turkmen",
    "Tuvaluan",
    "Ugandan",
    "Ukrainian",
    "Uruguayan",
    "Uzbek",
    "Vanuatuan",
    "Venezuelan",
    "Vietnamese",
    "Welsh",
    "Yemeni",
    "Zambian",
    "Zimbabwean"
]

f1_team_names = [
    "Apex Racing",
    "Vortex GP",
    "Black Falcon Motorsports",
    "Scuderia Orion",
    "Titan Velocity",
    "NovaSpeed Racing",
    "Equinox Motorsport",
    "Silver Arrow Racing",
    "Crimson Apex",
    "Thunderline GP",
    "Stellar Motorsport",
    "Ignite Racing Team",
    "Raven Dynamics",
    "Phantom Motorsport",
    "StormTech Racing",
    "Quantum Racing Works",
    "Valhalla GP",
    "Carbon Edge Racing",
    "Skyfire Motorsport",
    "Vanguard Velocity",
    "Obsidian GP",
    "Mirage Performance",
    "Stratospeed Racing",
    "Falcon Edge GP",
    "Shadowline Racing",
    "Ironclad Motorsports",
    "Tempest Racing",
    "Helix Grand Prix",
    "Zenith Racing Group",
    "Redshift Motorsport",
    "Draco GP",
    "Specter Racing",
    "Nexus F1 Team",
    "Hyperion Performance",
    "Ignis GP",
    "Altair Racing",
    "Forge Velocity",
    "Chronos Motorsport",
    "NeoRacer Team",
    "Lucent GP",
    "Solaris Racing",
    "Nebula GP",
    "Aurora Racing Technologies",
    "Falco Racing Team",
    "Kestrel GP",
    "Blackridge Motorsport",
    "Vertex Grand Prix",
    "ThrustLine Racing",
    "Inferno GP",
    "Pulse Motorsport",
    "Crater Racing",
    "Monarch GP",
    "ZeroPoint Racing",
    "Mythos Motorsport",
    "Axion GP",
    "Radiant Velocity",
    "Spectra F1",
    "BlazeLine GP",
    "Orion Works Racing",
    "Talon GP",
    "Veloce United",
    "Skyblade GP",
    "Polaris Motorsports",
    "Griffin Racing",
    "Onyx F1 Team",
    "Centauri Racing",
    "Jetstream GP",
    "Darkhorse Motorsports",
    "Volta GP",
    "Razorwind Racing",
    "Lightning Apex",
    "Machina Motorsport",
    "Spartan Velocity",
    "NovaPrime Racing",
    "TurboStratos GP",
    "Fireline Racing",
    "Seraphim GP",
    "ExoTech Racing",
    "Crimson Bolt GP",
    "Omega Velocity",
    "Eclipse F1",
    "Andromeda GP",
    "Nighthawk Motorsport",
    "Catalyst Racing",
    "TorqueOne GP",
    "Xenon Racing",
    "Striker GP",
    "Blue Nova Motorsports",
    "Gravitas GP",
    "Helion Performance",
    "Triton Racing",
    "Radon GP",
    "Ignition Racing Group",
    "Mistral Velocity",
    "Avalon Racing Team",
    "Zephyr GP",
    "Oblivion Motorsport",
    "NitroBolt GP",
    "Hydra Racing Technologies"
]

f1_driver_names = [
    "Luca Moretti",
    "Maxime Dubois",
    "Carlos Herrera",
    "Jack Thornton",
    "Niko Hakkinen",
    "Rafael Sato",
    "Victor Petrov",
    "Jonas Weber",
    "Tomasz Zielinski",
    "Andre Costa",
    "Marco Tanaka",
    "Felix van der Meer",
    "Ethan Cross",
    "Sebastian Keller",
    "Javier Alonzo",
    "Noah Lindström",
    "Dominic Russo",
    "Emil Johansson",
    "Oliver Clarke",
    "Kaito Nakamura",
    "Bruno Leclerc",
    "Milan Horvat",
    "Lucas Sørensen",
    "Artem Volkov",
    "Thiago Mendes",
    "Francesco Romano",
    "Damon Hartley",
    "Liam O’Connor",
    "João Ferreira",
    "Hugo Renaud",
    "Mikael Rask",
    "Alejandro Varga",
    "Kevin Blanchard",
    "Riku Yamashita",
    "Timo Reuter",
    "Jean-Paul Mercier",
    "Benji Shepherd",
    "Matteo Bianchi",
    "Sven Nyström",
    "Pavel Antonov",
    "Adrian Varga",
    "Felipe Navarro",
    "Oscar Munroe",
    "Zane Cooper",
    "Igor Kovalenko",
    "Rohan Malik",
    "Kai Müller",
    "Mateo Salcedo",
    "Danilo Greco",
    "Alexei Markov",
    "Tobias Bergström",
    "Tristan Wolfe",
    "Jens Eriksen",
    "Antonio Serra",
    "Enzo Marquez",
    "Daisuke Fujimoto",
    "Samir Rahman",
    "Finn Gallagher",
    "Olivier Bruneau",
    "Roman Tsvetkov",
    "Callum Drake",
    "Santiago Torres",
    "Leon Schneider",
    "Yuji Matsuda",
    "Andrei Nicolae",
    "Marcus Blackwood",
    "Kazuki Mori",
    "Julien Delacroix",
    "Niels van Dijk",
    "Hendrik Vos",
    "Sergio Blanco",
    "Nash Patel",
    "Luciano Grelli",
    "Hugo Steiner",
    "Aleksandar Mitrovic",
    "Tariq Al-Fulan",
    "Connor Whitmore",
    "Dmitri Sokolov",
    "Henrik Jansson",
    "Gabriel Fonseca",
    "Jamie Rowland",
    "Ilias Demetriou",
    "Kamil Nowak",
    "Frederik Olsen",
    "Marcel Dubcek",
    "Leonardo Rossi",
    "Yannick Dupuis",
    "Jorge Montoya",
    "Raheem Zahir",
    "Arjun Iyer",
    "Teo Popescu",
    "Patrick Lawson",
    "Ali Rezaei",
    "Giancarlo Ferri",
    "Rudi Baumann",
    "Bastien Chevalier",
    "Elias Pettersson",
    "Sebastián Correa",
    "Martin Kovac",
    "Kristof Nagy"
]


def generate_synthetic_data_csv(num_rows=1000):
    import pandas as pd
    import random
    from faker import Faker
    import coolname

    fake = Faker()

    num_rows = 500
    TEAM = {
        "team_name": [coolname.generate_slug(2) for _ in range(num_rows)],
        "location": [random.choice(locations) for _ in range(num_rows)],
    }
    # remove all rows with duplicate team_name
    TEAM = pd.DataFrame(TEAM).drop_duplicates(subset=["team_name"])

    TEAMdf = pd.DataFrame(TEAM)
    
    num_rows = 2000
    DRIVER = {
        "driver_id": [i for i in range(1, num_rows + 1)],
        "name": [fake.name() for _ in range(num_rows)],
        "nationality": [random.choice(nationalities) for _ in range(num_rows)],
    }

    DRIVERdf = pd.DataFrame(DRIVER)

    # circuit has circuit_name(str), location(str), no_of_turns(randint), length(float)

    num_rows = 300
    CIRCUIT = {
        "circuit_name": [f"Circuit {i}" for i in range(1, num_rows + 1)],
        "location": [random.choice(locations) for _ in range(num_rows)],
        "no_of_turns": [random.randint(10, 30) for _ in range(num_rows)],
        "length": [round(random.uniform(3.0, 7.0), 2) for _ in range(num_rows)],
    }


    CIRCUITdf = pd.DataFrame(CIRCUIT)

    num_rows = 600
    # sponsor has sponsor_name(company_name), industry
    SPONSOR = {
        "sponsor_name": [random.choice(company_names) for _ in range(num_rows)],
        "industry": [random.choice(industries) for _ in range(num_rows)],
    }

    # remove all rows with duplicate sponsor_name
    SPONSOR = pd.DataFrame(SPONSOR).drop_duplicates(subset=["sponsor_name"])

    SPONSORdf = pd.DataFrame(SPONSOR)

    num_rows = 10000
    # race_event has race_id(int), start_date(date), temp(float between 20 and 40), precipitation(float between 0 and 100), wind_speed(float between 0 and 20)
    from datetime import datetime, timedelta
    import random
    start_date = datetime(2023, 1, 1)
    RACE_EVENT = {
        "race_id": [i for i in range(1, num_rows + 1)],
        "start_date": [(start_date + timedelta(days=i)).strftime("%Y-%m-%d") for i in range(num_rows)],
        "temp": [round(random.uniform(20.0, 40.0), 2) for _ in range(num_rows)],
        "precipitation": [round(random.uniform(0.0, 100.0), 2) for _ in range(num_rows)],
        "wind_speed": [round(random.uniform(0.0, 20.0), 2) for _ in range(num_rows)],
    }

    RACE_EVENTdf = pd.DataFrame(RACE_EVENT)

    num_rows = 20000
    # race_results has result_id(int), driver_id(int), date(date), finish_position(int), no_laps(int)
    RACE_RESULTS = {
        "result_id": [i for i in range(1, num_rows + 1)],
        "driver_id": [random.choice(DRIVERdf["driver_id"].tolist()) for _ in range(num_rows)],
        "date": [(start_date + timedelta(days=i)).strftime("%Y-%m-%d") for i in range(num_rows)],
        "finish_position": [random.randint(1, 20) for _ in range(num_rows)],
        "no_laps": [random.randint(10, 100) for _ in range(num_rows)],
    }

    RACE_RESULTSdf = pd.DataFrame(RACE_RESULTS)
    

    num_rows = 50000
    # laptimes has result_id(int), time(float)
    LAPTIME = {
        # result_id is a random int between 1 and 20000
        "result_id": [random.randint(1, 20000) for _ in range(num_rows)],
        "time": [round(random.uniform(60.0, 120.0), 2) for _ in range(num_rows)],
    }
    LAPTIMEdf = pd.DataFrame(LAPTIME)

    num_rows = 500
    # employs has team_name(str), driver_id(int)
    EMPLOYS = {
        "team_name": [random.choice(f1_team_names) for _ in range(num_rows)],
        "driver_id": [i for i in range(1, num_rows + 1)],
    }
    EMPLOYSdf = pd.DataFrame(EMPLOYS)

    num_rows = 10000
    # competes_in has driver_id(int), race_id(int)
    COMPETES_IN = {
        "driver_id": [i for i in range(1, num_rows + 1)],
        "race_id": [i for i in range(1, num_rows + 1)],
    }

    COMPETES_INdf = pd.DataFrame(COMPETES_IN)

    num_rows = 10000
    # hosts has circuit_name(str), race_id(int)
    HOSTS = {
        "circuit_name": [f"Circuit {i}" for i in range(1, num_rows + 1)],
        "race_id": [i for i in range(1, num_rows + 1)],
    }
    HOSTSdf = pd.DataFrame(HOSTS)

    num_rows = 500
    # team_sponsor_pair has team_name(str), sponsor_name(str)
    TEAM_SPONSOR_PAIR = {
        "team_name": [random.choice(f1_team_names) for _ in range(num_rows)],
        "sponsor_name": [random.choice(company_names) for _ in range(num_rows)],
    }
    TEAM_SPONSOR_PAIRdf = pd.DataFrame(TEAM_SPONSOR_PAIR)

    num_rows = 20000
    # event_sponsor_pair has race_id(int), sponsor_name(str), where both race_id and sponsor_name are within the race_id's generated and sponsor_names generated
    EVENT_SPONSOR_PAIR = {
        "race_id": [random.randint(1, 10000) for _ in range(num_rows)],
        "sponsor_name": [random.choice(company_names) for _ in range(num_rows)],
    }
    EVENT_SPONSOR_PAIRdf = pd.DataFrame(EVENT_SPONSOR_PAIR)

    num_rows = 10000
    # event_results has race_id(int), result_id(int)
    EVENT_RESULTS = {
        "race_id": [random.randint(1, 10000) for _ in range(num_rows)],
        "result_id": [random.randint(1, 10000) for _ in range(num_rows)],
        "result_id": [i for i in range(1, num_rows + 1)],
    }
    EVENT_RESULTdf = pd.DataFrame(EVENT_RESULTS)

    # save all dataframes to csv files in new csv folder
    import os
    if not os.path.exists("csv"):
        os.makedirs("csv")
    TEAMdf.to_csv("csv/team.csv", index=False)
    DRIVERdf.to_csv("csv/driver.csv", index=False)
    CIRCUITdf.to_csv("csv/circuit.csv", index=False)
    SPONSORdf.to_csv("csv/sponsor.csv", index=False)
    RACE_EVENTdf.to_csv("csv/race_event.csv", index=False)
    RACE_RESULTSdf.to_csv("csv/race_results.csv", index=False)
    LAPTIMEdf.to_csv("csv/laptime.csv", index=False)
    EMPLOYSdf.to_csv("csv/employs.csv", index=False)
    COMPETES_INdf.to_csv("csv/competes_in.csv", index=False)
    HOSTSdf.to_csv("csv/hosts.csv", index=False)
    TEAM_SPONSOR_PAIRdf.to_csv("csv/team_sponsor_pair.csv", index=False)
    EVENT_SPONSOR_PAIRdf.to_csv("csv/event_sponsor_pair.csv", index=False)
    EVENT_RESULTdf.to_csv("csv/event_results.csv", index=False)
    print("Synthetic data generated and saved to csv folder.")





if __name__ == "__main__":
    generate_synthetic_data_csv(1000)